baseURL = "https://everydayapopalbum.netlify.app/"
title = "Everyday a Pop Album"
theme = "PaperMod"
defaultContentLanguage = "en"
languageCode = "en-us"
copyright = "Copyright © 2025 Everyday a Pop Album"

[params]
  author = "Everyday a Pop Album"
  description = "Discover a new pop album every day — Brazilian, Latin or International. Dive into pop music history and explore timeless classics and hidden gems."
  keywords = ["pop music", "daily album", "Brazilian pop", "Latin pop", "international pop", "music discovery", "pop classics", "album of the day", "hidden gems"]
  ShowReadingTime = true
  defaultTheme = "auto"
  disableThemeToggle = false
  [params.assets]
    customCSS = ["css/custom.css"]


[outputs]
  home = ["HTML", "RSS", "JSON", "SITEMAP"]

[languages]

  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content"

  [languages.pt]
    languageName = "Português"
    weight = 2
    contentDir = "content"

  [languages.es]
    languageName = "Español"
    weight = 3
    contentDir = "content"
