
baseURL = "https://everydayapopalbum.netlify.app/"
title = "Everyday a Pop Album"
theme = "PaperMod"
defaultContentLanguage = "en"
languageCode = "en-us"
copyright = "Copyright © 2025 Everyday a Pop Album"

[languages]
  [languages.en]
    title = "Everyday a Pop Album"
    weight = 1
  [languages.pt]
    title = "Um Álbum Pop por Dia"
    weight = 2

[params]
  author = "Everyday a Pop Album"
  description = "Discover a new pop album every day: Brazilian, Latin or international."
  ShowReadingTime = true
  defaultTheme = "auto"
  disableThemeToggle = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
